---
# file: roles/mysql-client/tasks/main.yml
- name: install mysql-client with apt
  when: aspects_mysql_client_enabled and ansible_os_family == "Debian"
  apt: 
    state: "present"
    pkg: "{{ aspects_mysql_client_package_name.Debian }}"
  tags:
    - aspects_mysql_client

- name: install mysql-client with yum
  when: aspects_mysql_client_enabled and ansible_os_family == "RedHat"
  yum: 
    state: "present" 
    pkg: "{{ aspects_mysql_client_package_name.RedHat }}"
  tags:
    - aspects_mysql_client